name: Release

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  publish-release:
    runs-on: ubuntu-latest
    name: Publish to GitHub
    if: "startsWith(github.ref, 'refs/tags/')"
    permissions:
      contents: write
    steps:
      - name: Get tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: ${{ env.RELEASE_VERSION }}
          body: |
            **Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ env.RELEASE_VERSION }}...HEAD
            
            This release mirrors typos ${{ env.RELEASE_VERSION }} from PyPI.
          draft: false
          prerelease: false
